from __future__ import annotations

import json
import re
import shutil
from datetime import datetime
from pathlib import Path

from .models import Message, MessageType


def _slugify(value: str) -> str:
    cleaned = re.sub(r"[<>:\"/\\|?*\x00-\x1f]", "-", value.strip())
    cleaned = re.sub(r"\s+", "-", cleaned)
    cleaned = re.sub(r"-+", "-", cleaned).strip("-.")
    return cleaned[:60] or "issue"


def _copy_asset(message: Message, source: Path, package_dir: Path) -> str:
    if message.type == MessageType.IMAGE:
        subdir = package_dir / "images"
        suffix = source.suffix.lower() or ".png"
        filename = f"{message.id}-image{suffix}"
    else:
        subdir = package_dir / "attachments"
        suffix = source.suffix.lower()
        safe_stem = _slugify(source.stem)
        filename = f"{message.id}-{safe_stem}{suffix}"
    subdir.mkdir(parents=True, exist_ok=True)
    target = subdir / filename
    shutil.copy2(source, target)
    return target.relative_to(package_dir).as_posix()


def render_issue_markdown(title: str, messages: list[Message]) -> str:
    lines = [f"# {title}", "", "> Generated by IssuePack. Original message order is preserved.", ""]
    for message in messages:
        header_bits = [bit for bit in (message.time, message.sender) if bit]
        lines.append(f"## {' · '.join(header_bits) or message.id}")
        lines.append("")
        if message.type == MessageType.TEXT:
            lines.append(message.content)
        elif message.type == MessageType.IMAGE:
            if message.asset_path:
                lines.append(f"![{message.id} customer image](./{message.asset_path})")
            else:
                lines.append(f"[未补充图片：{message.id}]")
        elif message.type == MessageType.FILE:
            if message.asset_path:
                lines.append(f"[附件：{Path(message.asset_path).name}](./{message.asset_path})")
            else:
                lines.append(f"[未补充文件：{message.id}]")
        lines.extend(["", f"<!-- source: {message.id} -->", ""])
    return "\n".join(lines).rstrip() + "\n"


def build_package(
    output_root: Path,
    title: str,
    messages: list[Message],
    captured_assets: dict[str, Path],
    now: datetime | None = None,
) -> Path:
    now = now or datetime.now()
    folder = f"{now:%Y-%m-%d-%H%M%S}-{_slugify(title)}"
    package_dir = output_root.expanduser().resolve() / folder
    if package_dir.exists():
        raise FileExistsError(f"Issue Package 已存在: {package_dir}")

    (package_dir / "raw").mkdir(parents=True, exist_ok=False)

    finalized: list[Message] = []
    for source_message in messages:
        message = Message(
            id=source_message.id,
            sender=source_message.sender,
            time=source_message.time,
            type=source_message.type,
            content=source_message.content,
            source_header=source_message.source_header,
            asset_path=source_message.asset_path,
        )
        asset = captured_assets.get(message.id)
        if asset is not None:
            message.asset_path = _copy_asset(message, asset, package_dir)
        finalized.append(message)

    raw_payload = {
        "schema_version": "0.1",
        "created_at": now.isoformat(timespec="seconds"),
        "title": title,
        "messages": [message.to_dict() for message in finalized],
    }
    (package_dir / "raw" / "conversation.json").write_text(
        json.dumps(raw_payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (package_dir / "issue.md").write_text(render_issue_markdown(title, finalized), encoding="utf-8")
    (package_dir / "result.md").write_text(
        "# Resolution\n\n"
        "## Requirement understood\n\n"
        "_To be completed by the coding agent._\n\n"
        "## Files changed\n\n"
        "## Verification\n\n"
        "## Remaining uncertainties\n",
        encoding="utf-8",
    )
    return package_dir
